---
fireactions_version: 1.0.0
fireactions_arch: amd64
fireactions_url: |
  https://github.com/hostinger/fireactions/releases/download/v{{ fireactions_version }}/fireactions-v{{ fireactions_version }}-linux-{{ fireactions_arch }}.tar.gz
fireactions_install_dir: /opt/fireactions/{{ fireactions_version }}
fireactions_group: root
fireactions_owner: root
fireactions_service_state: started

fireactions_config_dir: /etc/fireactions
fireactions_config_file_path: "{{ fireactions_config_dir }}/config.yaml"
fireactions_config: {}
